/* Module Clients / Tiers — table public.parties (112 lignes) */
kra.registerModule('clients', {
  table: 'parties',
  title: 'Clients / Tiers',
  searchCols: ['party_code','legal_name','trade_name','display_name','email','phone','city','nif','siret'],
  orderBy: {col: 'updated_at', asc: false},
  pageSize: 25,
  columns: [
    {key:'party_code', label:'Code', width:'110px'},
    {key:'display_name', label:'Nom affiché', fmt:(v,r)=> kra.esc(v || r.legal_name || r.trade_name || '')},
    {key:'party_type', label:'Type', width:'130px', fmt:(v)=> v ? `<span class="tag neutral">${kra.esc(v)}</span>` : ''},
    {key:'email', label:'Email'},
    {key:'phone', label:'Téléphone', width:'140px'},
    {key:'city', label:'Ville', width:'130px'},
    {key:'status', label:'Statut', width:'100px', fmt:(v)=> v==='active' ? '<span class="tag">actif</span>' : (v ? `<span class="tag neutral">${kra.esc(v)}</span>` : '')},
  ],
  fields: [
    {name:'party_code', label:'Code tiers', type:'text', hint:'Code interne (laisser vide pour génération)'},
    {name:'party_type', label:'Type', type:'select', opts:[
      {value:'customer', label:'Client'},
      {value:'forwarder', label:'Transitaire'},
      {value:'shipper', label:'Chargeur'},
      {value:'grouper', label:'Groupeur'},
      {value:'supplier', label:'Fournisseur'},
      {value:'carrier', label:'Transporteur'},
      {value:'exporter', label:'Exportateur'},
      {value:'partner', label:'Partenaire'},
    ]},
    {name:'display_name', label:'Nom affiché', type:'text', required:true},
    {name:'legal_name', label:'Raison sociale', type:'text'},
    {name:'trade_name', label:'Nom commercial', type:'text'},
    {name:'first_name', label:'Prénom', type:'text'},
    {name:'last_name', label:'Nom', type:'text'},
    {name:'email', label:'Email', type:'email'},
    {name:'phone', label:'Téléphone', type:'text'},
    {name:'address', label:'Adresse', type:'textarea'},
    {name:'postal_code', label:'Code postal', type:'text'},
    {name:'city', label:'Ville', type:'text'},
    {name:'country', label:'Pays', type:'text', hint:'Code ou libellé'},
    {name:'nif', label:'NIF', type:'text'},
    {name:'siret', label:'SIRET', type:'text'},
    {name:'eori', label:'EORI', type:'text'},
    {name:'status', label:'Statut', type:'select', default:'active', required:true, opts:[
      {value:'active',label:'Actif'},{value:'inactive',label:'Inactif'},{value:'prospect',label:'Prospect'},{value:'blocked',label:'Bloqué'}
    ]},
    {name:'is_customer', label:'Client', type:'checkbox'},
    {name:'is_forwarder', label:'Transitaire', type:'checkbox'},
    {name:'is_shipper', label:'Chargeur', type:'checkbox'},
    {name:'is_grouper', label:'Groupeur', type:'checkbox'},
    {name:'is_supplier', label:'Fournisseur', type:'checkbox'},
    {name:'is_carrier', label:'Transporteur', type:'checkbox'},
    {name:'is_exporter', label:'Exportateur', type:'checkbox'},
    {name:'is_partner', label:'Partenaire', type:'checkbox'},
  ]
});
